# [desc] Serve a folder's SYMBOLS.md / the root AGENTS.md: hash-fresh -> serve free, stale -> one guarded LLM call. [/desc]
from __future__ import annotations

import os
import time
from pathlib import Path

from . import contract, inputs, regen
from .manifest import (
    AGENTS_DOC,
    SYMBOLS_DOC,
    code_files,
    feature_enabled,
    folder_manifest,
    split_frontmatter,
    staleness,
    tree_sha,
)

LOCK_TTL_S = 120
_SELF_AUTHORED: set[str] = set()


def mark_self_authored(folder: Path) -> None:
    """This agent just wrote code here — do not bill it for regenerating its own churn."""
    _SELF_AUTHORED.add(str(Path(folder).resolve()))


def _is_self_authored(folder: Path) -> bool:
    return str(folder.resolve()) in _SELF_AUTHORED


def _body(doc: Path) -> str:
    """The document without its frontmatter — the manifest is machinery, not content."""
    _, body = split_frontmatter(doc.read_text(encoding="utf-8"))
    return body.strip()


def _stale_notice(doc: Path, reasons: list[str], why: str) -> str:
    return (
        f"{_body(doc)}\n\n---\n"
        f"[stale — {why}. Out of date because: {', '.join(reasons[:4])}. "
        f"Verify anything you rely on with Read(symbol=...).]"
    )


def _atomic_write(doc: Path, text: str) -> None:
    """Never let a neighbour read a half-written map."""
    if doc.exists() and doc.read_text(encoding="utf-8") == text:
        return
    tmp = doc.with_suffix(doc.suffix + f".tmp{os.getpid()}")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, doc)


def _take_lock(doc: Path) -> int | None:
    """``O_EXCL`` lock beside the doc. None when someone else holds a fresh one."""
    lock = doc.with_suffix(doc.suffix + ".lock")
    if lock.exists() and time.time() - lock.stat().st_mtime < LOCK_TTL_S:
        return None
    lock.unlink(missing_ok=True)
    return os.open(str(lock), os.O_CREAT | os.O_EXCL | os.O_WRONLY)


def _release(doc: Path, fd: int) -> None:
    os.close(fd)
    doc.with_suffix(doc.suffix + ".lock").unlink(missing_ok=True)


def symbol_map(folder: Path, root: Path, client=None, model: str | None = None) -> str:
    """The folder's symbol map. Fresh hash costs nothing; stale costs one LLM call."""
    folder, root = Path(folder).resolve(), Path(root).resolve()
    doc = folder / SYMBOLS_DOC
    if not code_files(folder):
        return f"No code files in {folder.name}/ — it has no SYMBOLS.md by design."
    model = model or regen.model_name()
    reasons = staleness(doc, {"files": folder_manifest(folder)}, model)

    if not reasons:
        return _body(doc)
    if not feature_enabled():
        return _body(doc) if doc.exists() else "SYMBOLS.md missing and regeneration is disabled."
    if doc.exists() and _is_self_authored(folder):
        return _stale_notice(doc, reasons, "you edited this folder yourself this session")

    def conforms(body: str) -> list[str]:
        return contract.validate(body, regen.legal_identifiers(folder), folder)

    return _regenerate(doc, reasons, conforms, lambda fb: (
        regen.generate_symbols(folder, root, client or _client(), model, fb),
        regen.symbols_manifest(folder, model),
    ))


def agents_map(root: Path, client=None, model: str | None = None) -> str:
    """The repository structure map. Invalidated only by the tree shape changing."""
    root = Path(root).resolve()
    doc = root / AGENTS_DOC
    model = model or regen.model_name()
    reasons = staleness(doc, {"tree_sha256": tree_sha(root)}, model)

    if not reasons:
        return _body(doc)
    if not feature_enabled():
        return _body(doc) if doc.exists() else "AGENTS.md missing and regeneration is disabled."
    current = _body(doc) if doc.exists() else "(none — first generation)"
    folders = inputs.code_folder_paths(root)

    def conforms(body: str) -> list[str]:
        return contract.validate_root(body, folders)

    return _regenerate(doc, reasons, conforms, lambda fb: (
        regen.generate_agents(root, current, reasons, client or _client(), model, fb),
        regen.agents_manifest(root, model),
    ))


def _regenerate(doc: Path, reasons: list[str], conforms, produce) -> str:
    fd = _take_lock(doc)
    if fd is None:
        if doc.exists():
            return _stale_notice(doc, reasons, "another agent is regenerating it right now")
        return "Map is being generated by another agent — retry in a moment."
    try:
        try:
            body, doc_manifest, violations = _produce_valid(produce, conforms)
        except Exception as exc:
            # LLM gateways return transient 503s. A map is an aid, never a reason to
            # lose a turn: serve what we have, say why, and let the next read retry.
            if doc.exists():
                return _stale_notice(doc, reasons, f"regeneration failed ({type(exc).__name__})")
            return f"Could not generate the map: {type(exc).__name__}: {exc}"
        if violations:
            if doc.exists():
                return _stale_notice(doc, reasons, f"contract breach: {violations[0]}")
            return f"Generation did not meet the contract: {'; '.join(violations)}"
        _atomic_write(doc, regen.compose(body, doc_manifest))
        return body.strip()
    finally:
        _release(doc, fd)


def _produce_valid(produce, conforms):
    """Generate, and on a contract breach retry ONCE with the findings fed back.

    The validator knows exactly which edge the AST contradicts, which range is
    wrong, which folders never got a row — that is precisely the information the
    model lacked. One retry, then we keep the previous map rather than write
    something false. The ROOT map is checked here too: it used to be written
    unexamined, which is how a generation cut at max_tokens landed on disk
    missing 34 folders and saying nothing about it.
    """
    feedback = ""
    body = doc_manifest = None
    violations: list[str] = []
    for _ in range(2):
        body, doc_manifest = produce(feedback)
        violations = conforms(body)
        if not violations:
            return body, doc_manifest, []
        feedback = "\n".join(f"- {v}" for v in violations)
    return body, doc_manifest, violations


def _client():
    import anthropic
    import httpx

    verify = os.environ.get("BOUZECODE_SSL_NO_VERIFY") != "1"
    return anthropic.Anthropic(
        base_url=os.environ.get("ANTHROPIC_BASE_URL") or None,
        api_key=os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("ANTHROPIC_AUTH_TOKEN"),
        http_client=httpx.Client(
            timeout=httpx.Timeout(connect=15, read=300, write=60, pool=15), verify=verify
        ),
        max_retries=3,
    )
