# [desc] What the packaging must declare: uv.lock ignored, and every runtime/test dependency named. [/desc]
"""Three omissions a fresh clone runs into.

`uv.lock` is generated by the first `uv run` and was not ignored, so it sat in
`git status` waiting to be committed by accident. `pytest-timeout` was missing
from the test extra, which turned `@pytest.mark.timeout(90)` into an
`PytestUnknownMarkWarning` and a timeout that never fired. `tqdm` is imported by
RunPythonTest and the folder-description analyzer but was declared nowhere — it
only ever arrived as a transitive dependency of another package.
"""
from __future__ import annotations

import tomllib
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[4]
_PYPROJECT = tomllib.loads((_REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))


def _ignored_patterns() -> list[str]:
    lines = (_REPO_ROOT / ".gitignore").read_text(encoding="utf-8").splitlines()
    return [line.strip() for line in lines if line.strip() and not line.startswith("#")]


def _declared(names: list[str]) -> set[str]:
    """Bare distribution names, stripped of their version specifiers."""
    return {name.split(">")[0].split("=")[0].split("[")[0].strip() for name in names}


def test_the_generated_lockfile_is_git_ignored():
    assert "uv.lock" in _ignored_patterns()


def test_the_generated_readme_sync_locks_are_git_ignored():
    ignored = _ignored_patterns()
    assert ".readme.lock" in ignored and ".agents.lock" in ignored


def test_the_test_extra_declares_the_timeout_plugin():
    extras = _PYPROJECT["project"]["optional-dependencies"]
    assert "pytest-timeout" in _declared(extras["test"])


def test_tqdm_is_a_declared_runtime_dependency():
    assert "tqdm" in _declared(_PYPROJECT["project"]["dependencies"])


def test_the_timeout_marker_is_actually_usable():
    """The plugin has to be installed, not only declared, for the mark to fire."""
    import pytest_timeout  # noqa: F401
