# [desc] Ce que l'empaquetage doit déclarer : uv.lock ignoré, dépendances nommées, aucun test dans la wheel. [/desc]
"""Four omissions a fresh clone — or a user installing the wheel — runs into.

`uv.lock` is generated by the first `uv run` and was not ignored, so it sat in
`git status` waiting to be committed by accident. `pytest-timeout` was missing
from the test extra, which turned `@pytest.mark.timeout(90)` into an
`PytestUnknownMarkWarning` and a timeout that never fired. `tqdm` is imported by
RunPythonTest and the folder-description analyzer but was declared nowhere — it
only ever arrived as a transitive dependency of another package.

And the wheel shipped 147 test modules. `exclude = ["tests*"]` only matches the
top-level `tests`, while `namespaces = true` (the default under `[tool.setuptools.
packages.find]`) picks up a test directory even without an `__init__.py`: every
`bouzecode.web_v2.tests.*`, `bouzecode.web_v2.runtime.tests` and `readme_sync.tests`
module travelled to the user. Nothing imports them at runtime.
"""
from __future__ import annotations

import tomllib
from fnmatch import fnmatch
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[4]
_PYPROJECT = tomllib.loads((_REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
_FIND = _PYPROJECT["tool"]["setuptools"]["packages"]["find"]

# `bouzecode/backend/tools/ops/test_runner.py` is NOT a test: it is the RunPythonTest
# tool, and the wheel needs it. It is the only module whose name starts with `test_`
# that legitimately ships; three others sitting in production packages
# (test_anthropic_helpers_gateway_retry, test_shell_search_deferred, test_migrations)
# were real tests nobody collected, and have been moved into test directories.
_PRODUCTION_MODULES_NAMED_LIKE_TESTS = {"bouzecode/backend/tools/ops/test_runner.py"}


def _packaging_roots() -> list[Path]:
    return [(_REPO_ROOT / where).resolve() for where in _FIND["where"]]


def _dotted(root: Path, directory: Path) -> str:
    return ".".join(directory.relative_to(root).parts)


def _candidate_test_packages() -> list[str]:
    """Dotted names of every directory named `tests`, and everything under it."""
    names = []
    for root in _packaging_roots():
        for tests_dir in root.rglob("tests"):
            if not tests_dir.is_dir() or "__pycache__" in tests_dir.parts:
                continue
            if any(part in (".venv", "build", "node_modules") for part in tests_dir.parts):
                continue
            names.append(_dotted(root, tests_dir))
            names += [_dotted(root, sub) for sub in tests_dir.rglob("*")
                      if sub.is_dir() and "__pycache__" not in sub.parts]
    return sorted(set(names))


def _ignored_patterns() -> list[str]:
    lines = (_REPO_ROOT / ".gitignore").read_text(encoding="utf-8").splitlines()
    return [line.strip() for line in lines if line.strip() and not line.startswith("#")]


def _declared(names: list[str]) -> set[str]:
    """Bare distribution names, stripped of their version specifiers."""
    return {name.split(">")[0].split("=")[0].split("[")[0].strip() for name in names}


def test_the_generated_lockfile_is_git_ignored():
    assert "uv.lock" in _ignored_patterns()


def test_the_generated_readme_sync_locks_are_git_ignored():
    ignored = _ignored_patterns()
    assert ".readme.lock" in ignored and ".agents.lock" in ignored


def test_the_test_extra_declares_the_timeout_plugin():
    extras = _PYPROJECT["project"]["optional-dependencies"]
    assert "pytest-timeout" in _declared(extras["test"])


def test_tqdm_is_a_declared_runtime_dependency():
    assert "tqdm" in _declared(_PYPROJECT["project"]["dependencies"])


def test_the_timeout_marker_is_actually_usable():
    """The plugin has to be installed, not only declared, for the mark to fire."""
    import pytest_timeout  # noqa: F401


def test_no_test_directory_escapes_the_packaging_excludes():
    """Every `tests` directory under a packaging root must be excluded by name."""
    excludes = _FIND["exclude"]
    unshielded = [name for name in _candidate_test_packages()
                  if not any(fnmatch(name, pattern) for pattern in excludes)]

    assert unshielded == [], (
        "These test packages would be installed with bouzecode; widen "
        f"`packages.find.exclude` (currently {excludes}):\n  " + "\n  ".join(unshielded)
    )


def test_no_test_module_hides_inside_a_shipped_package():
    """A stray `test_*.py` in a production package ships whatever the excludes say.

    Excluding packages cannot drop a single module, so a test file dropped next to the
    code it covers is both invisible to `testpaths` and visible to the user. Three of
    them had accumulated."""
    excludes = _FIND["exclude"]
    strays = set()
    for root in _packaging_roots():
        for module in root.rglob("test_*.py"):
            parts = module.relative_to(root).parts
            if "tests" in parts or "__pycache__" in parts:
                continue
            if any(part in (".venv", "build", "node_modules") for part in parts):
                continue
            # `where` lists both "src" and ".", so the src/ layout is seen twice; the
            # second sighting is what `exclude = ["src*", …]` is there to drop.
            package = ".".join(parts[:-1])
            if any(fnmatch(package, pattern) for pattern in excludes):
                continue
            strays.add("/".join(parts))

    assert sorted(strays) == sorted(_PRODUCTION_MODULES_NAMED_LIKE_TESTS), (
        "Test modules living inside production packages — move them into a `tests` "
        f"directory so they are collected and not shipped:\n  {sorted(strays)}"
    )
